#pragma once

enum AutoIndex { ON, OFF };
enum HttpMethod { GET, POST, DELETE };
enum ConfigTokenType { WORD, RIGHT_BRACE, LEFT_BRACE, SEMICOLON, EOF_TOKEN, COMMENT, NEWLINE };

enum ConfigDirectiveType { 
    ROOT_SERVER, ROOT_HTTP, ROOT_LOCATION, ROOT_LISTEN, ROOT_VALUE, ROOT_INDEX,
    SERVER_LISTEN, SERVER_LOCATION, SERVER_NAME, CLIENT_MAX_BODY_SIZE, ERROR_PAGE,
    LOCATION_ROOT, LOCATION_INDEX, LOCATION_METHODS,
    UNKNOWN
};
