#ifndef ENUMS_HPP
#define ENUMS_HPP

enum AutoIndex { ON, OFF };
enum HttpMethod { GET, POST, DELETE, PUT, HEAD, CONNECT, OPTIONS, TRACE, PATCH };
enum HttpStatusCode {
    OK = 200, CREATED = 201, NO_CONTENT = 204,
    MOVED_PERMANENTLY = 301, FOUND = 302,
    BAD_REQUEST = 400, FORBIDDEN = 403, NOT_FOUND = 404,
    METHOD_NOT_ALLOWED = 405, PAYLOAD_TOO_LARGE = 413,
    REQUEST_HEADER_FIELDS_TOO_LARGE = 431,
    INTERNAL_SERVER_ERROR = 500, GATEWAY_TIMEOUT = 504
};
enum ConfigTokenType { WORD, RIGHT_BRACE, LEFT_BRACE, SEMICOLON, EOF_TOKEN, COMMENT, NEWLINE };

enum ConfigDirectiveType { 
    UNKNOWN, ROOT_SERVER, ROOT_HTTP,
    SERVER_LISTEN, SERVER_LOCATION, SERVER_ROOT, SERVER_NAMES, SERVER_CLIENT_MAX_BODY_SIZE, SERVER_ERROR_PAGE,
    LOCATION_ROOT, LOCATION_INDEX, LOCATION_METHODS, LOCATION_LIMITS_EXCEPT, LOCATION_AUTOINDEX, LOCATION_UPLOAD_STORE, LOCATION_CGI_PASS, LOCATION_REDIRECT, LOCATION_ERROR_PAGE,
};

enum HttpRequestAttribute {
    method, uri_path, version, headers, query_parameters, body
};

#endif