server {
    listen localhost:8080;
    error_page 404 /404.html;
    error_page 500 502 503 504 /50x.html;
    client_max_body_size 10M;
    location / {
        root /var/www/html;
        index index.html;
        limit_except GET POST DELETE;
        autoindex off;
    }
    location /uploads {
        root /var/www;
        limit_except POST;
        autoindex off;
        upload_store /var/www/uploads;
    }
    location /cgi-bin {
        root /var/www;
        limit_except GET POST;
        cgi_pass .php;
    }
}