server {
    listen 8080;
    server_name localhost;
    root /var/www/html;
    client_max_body_size 1M;
    
    location / {
        index index.html;
        autoindex off;
    }
    
    location /upload {
        upload_enabled on;
        upload_dir /var/www/uploads;
        allowed_methods POST GET;
    }
}
