server {
    # Comentario escondido pro parser ignorar
    listen 8080;

    # Comentario escondido pro parser ignorar
    root /var/www/html;
    
    location /admin {
        autoindex on;
    }
}
